# Generated by Django 5.0 on 2024-12-04 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarius', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='supporters',
            field=models.ManyToManyField(related_name='author_supporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
