# Generated by Django 5.0 on 2024-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarius', '0002_author_supporters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
