# Generated by Django 5.0 on 2024-12-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarius', '0003_alter_author_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(choices=[(1, 'Bad!'), (2, 'Not good'), (3, 'Ok'), (4, 'Well done!'), (5, 'Incredible!')], help_text='Rate the book from 1 to 5.', verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarius.book')),
            ],
        ),
    ]
